# Generated by Django 5.1.3 on 2025-02-03 14:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0019_favoritos_itensfavoritos"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="favoritos",
            name="cidade",
        ),
        migrations.RemoveField(
            model_name="favoritos",
            name="email",
        ),
        migrations.RemoveField(
            model_name="favoritos",
            name="nome",
        ),
        migrations.RemoveField(
            model_name="favoritos",
            name="site",
        ),
    ]
