# Generated by Django 5.1.3 on 2025-02-06 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0021_favoritos_cidade_favoritos_email_favoritos_nome_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="favoritos",
            name="nome",
            field=models.CharField(default="Nome Padrão", max_length=100),
        ),
    ]
