# Generated by Django 5.1.3 on 2025-02-06 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0022_alter_favoritos_nome"),
    ]

    operations = [
        migrations.AlterField(
            model_name="favoritos",
            name="nome",
            field=models.CharField(max_length=100),
        ),
    ]
