# Generated by Django 5.1.3 on 2025-02-06 13:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0024_remove_favoritos_cidade_remove_favoritos_email_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="favoritos",
            name="usuario",
            field=models.ForeignKey(
                default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
            preserve_default=False,
        ),
    ]
