# Generated by Django 5.1.3 on 2025-02-06 13:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0025_favoritos_usuario"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Favoritos",
            new_name="Favorito",
        ),
    ]
